name: Run JS Script with Secret

on: [push]  # or change to 'workflow_dispatch' for manual runs

jobs:
  run-js:
    runs-on: ubuntu-latest
    env:
      TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run JavaScript file
        run: |
          npm install dotenv
          node blog.js
          node admin.js
